import { constants } from 'node:fs';
import { copyFile,lstat,mkdir,opendir,readFile,rename,rm } from 'node:fs/promises';
import path from 'node:path';
import { SCHEMAS,authority,exactIdentity,fail,hashFile,readJson,selfHash,stableJson,stableFile,verifySelfHash,writeCreateOnly } from './lib.mjs';
import { verifyPlan } from './plan.mjs';
async function exactCopy(source,target,expected){const before=await stableFile(source,expected.sourceRelativePath);exactIdentity(before,{...expected,sha256:expected.sourceSha256,bytes:expected.sourceBytes});await mkdir(path.dirname(target),{recursive:true});await copyFile(source,target,constants.COPYFILE_EXCL);const copied=await hashFile(target);exactIdentity(copied,{...expected,sha256:expected.sourceSha256,bytes:expected.sourceBytes});const after=await stableFile(source,expected.sourceRelativePath);exactIdentity(after,{...expected,sha256:expected.sourceSha256,bytes:expected.sourceBytes})}
async function list(root){const out=[];async function visit(dir){const entries=[];for await(const e of await opendir(dir))entries.push(e);entries.sort((a,b)=>a.name.localeCompare(b.name,'en'));for(const e of entries){const p=path.join(dir,e.name),rel=path.relative(root,p).split(path.sep).join('/');if(e.isSymbolicLink())fail('RAW_ART_SESSION_SYMLINK',`Session contains symlink ${rel}.`);if(e.isDirectory())await visit(p);else if(e.isFile()){const h=await hashFile(p);out.push({relativePath:rel,...h})}else fail('RAW_ART_SESSION_ENTRY_INVALID',`Session contains invalid entry ${rel}.`)}}await visit(root);return out}
export async function materializeRawArtSession(options){const read=await readJson(options.planPath,'plan'),plan=verifyPlan(read.value),final=path.resolve(plan.sessionRoot),parent=path.dirname(final),temporary=path.join(parent,`.${path.basename(final)}.${process.pid}.${Date.now()}.tmp`);try{await lstat(final);fail('RAW_ART_SESSION_EXISTS',`Session exists: ${final}.`)}catch(e){if(e?.code!=='ENOENT')throw e}await mkdir(parent,{recursive:true});await mkdir(temporary,{recursive:false,mode:0o700});try{for(const op of plan.operations){const source=path.join(plan.rawArtRoot,...op.sourceRelativePath.split('/')),target=path.join(temporary,...op.targetRelativePath.split('/'));await exactCopy(source,target,op)}const inventoryBytes=await readFile(plan.inventoryPath);await writeCreateOnly(path.join(temporary,'manifests','inventory.json'),inventoryBytes);await writeCreateOnly(path.join(temporary,'manifests','plan.json'),Buffer.from(stableJson(plan),'utf8'));const declared=await list(temporary),doc={schema:SCHEMAS.manifest,sessionId:plan.sessionId,planSha256:plan.planSha256,createdAt:new Date().toISOString(),files:Object.freeze(declared),authority};const manifest=Object.freeze({...doc,manifestSha256:selfHash(doc,'manifestSha256')});await writeCreateOnly(path.join(temporary,'manifests','session.json'),Buffer.from(stableJson(manifest),'utf8'));await rename(temporary,final);return Object.freeze({status:'materialized',sessionRoot:final,planSha256:plan.planSha256,manifestSha256:manifest.manifestSha256,filesCopied:plan.operations.length})}catch(e){await rm(temporary,{recursive:true,force:true});throw e}}
export async function verifyRawArtSession(options){const root=path.resolve(options.sessionRoot),manifestPath=path.join(root,'manifests','session.json'),read=await readJson(manifestPath,'session manifest'),manifest=verifySelfHash(read.value,'manifestSha256','RAW_ART_SESSION_MANIFEST_HASH_MISMATCH');if(manifest.schema!==SCHEMAS.manifest)fail('RAW_ART_SESSION_MANIFEST_INVALID','Session manifest schema differs.');const actual=await list(root),byPath=new Map(actual.map(f=>[f.relativePath,f])),declared=new Map(manifest.files.map(f=>[f.relativePath,f]));for(const [p,expected] of declared){const found=byPath.get(p);if(!found)fail('RAW_ART_SESSION_FILE_MISSING',`Missing ${p}.`);exactIdentity(found,expected,'RAW_ART_SESSION_FILE_MISMATCH')}for(const p of byPath.keys())if(p!=='manifests/session.json'&&!declared.has(p))fail('RAW_ART_SESSION_FILE_UNDECLARED',`Undeclared ${p}.`);return Object.freeze({status:'passed',sessionRoot:root,manifestSha256:manifest.manifestSha256,verifiedFiles:declared.size})}
