import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { compileRoadSignSession, verifyRoadSignSession, validateRoadSignSpec, sha256 } from "./rally-25d-road-sign-jobs.mjs";
const SPEC_PATH=new URL("../../config/game-art-production/props/road-sign-production-v1.json",import.meta.url);
const load=async()=>JSON.parse(await readFile(SPEC_PATH,"utf8"));
function rehash(session){const body=Object.fromEntries(Object.entries(session).filter(([key])=>key!=="sessionSha256"));session.sessionSha256=sha256(body);return session;}
test("compiles deterministic ten-image road-sign kit",async()=>{const spec=await load();const before=JSON.stringify(spec);const first=compileRoadSignSession(spec);const second=compileRoadSignSession(spec);assert.equal(first.sessionSha256,second.sessionSha256);assert.equal(first.totals.jobs,10);assert.equal(first.totals.images,10);assert.equal(first.totals.variants,3);assert.equal(first.totals.modelingJobs,4);assert.equal(first.totals.damageJobs,2);assert.equal(new Set(first.jobs.map((job)=>job.output.master)).size,10);assert.ok(first.jobs.every((job)=>job.images===1));assert.equal(first.readiness.downstream3DReady,false);assert.equal(first.authority.providerExecution,false);assert.equal(JSON.stringify(spec),before);assert.equal(verifyRoadSignSession(first),true);});
test("rejects cycles and missing dependencies",async()=>{const cycle=await load();cycle.jobs[0].dependsOn=[cycle.jobs.at(-1).id];assert.throws(()=>compileRoadSignSession(cycle),/cycle/i);const missing=await load();missing.jobs[6].dependsOn=["unknown-reference"];assert.throws(()=>compileRoadSignSession(missing),/unknown dependency/i);});
test("rejects combined layouts and weak role closure",async()=>{const layout=await load();layout.jobs[0].include.push("contact sheet of sign variants");assert.throws(()=>validateRoadSignSpec(layout),/combined layout/i);const closure=await load();closure.jobs[3].role="variant-identity";assert.throws(()=>validateRoadSignSpec(closure),/four modular modeling references/i);});
test("rejects coercive camera and authority metadata",async()=>{const camera=await load();camera.cameraLocks.heroPitchDegrees="24";assert.throws(()=>compileRoadSignSession(camera),/finite number/i);const authority=await load();authority.authority.providerExecution=true;assert.throws(()=>compileRoadSignSession(authority),/must remain false/i);});
test("rejects attacker-rehashed session drift",async()=>{const session=compileRoadSignSession(await load());const forged=structuredClone(session);forged.jobs[3].target.width=4096;rehash(forged);assert.throws(()=>verifyRoadSignSession(forged),/deterministic compilation/i);});
