import type { ArtDirectionCompileRequestInput } from "@evavo/art-direction";

export const DEFAULT_ART_DIRECTION_REQUEST = {
  schemaVersion: "1.0",
  contractId: "brass-brine-deckhand-walk-direction",
  presetId: "isometric-rpg-1997",
  project: {
    projectId: "brass-brine",
    title: "Brass & Brine",
    engine: "Godot",
    engineVersion: "4.6.2",
    gameGenre: "historical maritime trading role-playing game",
    targetPlatform: "desktop and mobile",
    viewport: { width: 1280, height: 720 },
    worldScale: {
      pixelsPerTile: 64,
      characterHeightPixels: 96,
      tileWidthPixels: 64,
      tileHeightPixels: 32,
    },
  },
  style: {
    intent:
      "Create a late-1990s isometric deckhand animation that belongs to the same authored maritime world across every direction, frame, UI portrait and environmental interaction.",
    mustHave: [
      "clear deckhand silhouette at gameplay scale",
      "historically plausible 1871 work clothing",
      "stable coat, cap, boots and body proportions",
      "readable feet and ground contact",
      "restrained maritime wear rather than decorative clutter",
    ],
    mustAvoid: [
      "generic fantasy armour",
      "modern tactical equipment",
      "random straps, pouches or glowing accents",
      "different lighting between directions",
      "independent frame redesign",
    ],
    materialLanguage: [
      "worn wool and canvas",
      "salt-dulled leather",
      "restrained brass and iron fittings",
    ],
    lineTreatment: [
      "deliberate pixel clusters",
      "clean 2:1 isometric silhouette",
      "selective dark contour without accidental antialiasing",
    ],
    compositionRules: [
      "feet remain on the shared Y-sort origin",
      "cast shadow stays a separate registered layer",
      "full motion bounds remain inside the transparent canvas",
    ],
    antiGeneric: {
      requiredDistinctiveMotifs: [
        "Reconstruction-era maritime workwear",
        "project-specific deckhand coat and cap construction",
      ],
      prohibitedGenericMotifs: [
        "AI-like ornamental clutter",
        "unrequested belts and satchels",
        "fantasy pirate costume",
        "random smoke or magical atmosphere",
      ],
      prohibitUnrequestedProps: true,
      prohibitReadableText: true,
      prohibitWatermarks: true,
      prohibitModernGloss: true,
      prohibitRandomMicrodetail: true,
      prohibitStyleDrift: true,
      requireHistoricalPlausibility: true,
    },
    references: [
      {
        id: "deckhand-identity-master",
        role: "identity",
        uri: "artifact://projects/brass-brine/characters/deckhand/canonical-identity",
        weight: 1,
        note: "Approved proportions, costume construction, face and silhouette.",
        rights: "EVAVO project-owned source art.",
      },
      {
        id: "brass-brine-palette",
        role: "palette",
        uri: "artifact://projects/brass-brine/style/palette-master",
        weight: 1,
        note: "Approved indexed palette and value ramps.",
        rights: "EVAVO project-owned style asset.",
      },
      {
        id: "maritime-1871-reference",
        role: "historical",
        uri: "reference://brass-brine/research/1871-maritime-workwear",
        weight: 0.9,
        note: "Curated clothing, material and equipment evidence for 1871 deck labour.",
        rights: "Research reference only; do not copy protected artwork.",
      },
    ],
  },
  asset: {
    assetId: "deckhand-walk",
    family: "character",
    purpose: "Eight-direction gameplay walk cycle with runtime clothing and equipment variants.",
    dimensions: { width: 96, height: 128 },
    transparency: "required",
    animated: true,
    frameCount: 8,
    framesPerSecond: 8,
    loop: true,
    directionCount: 8,
    directionNames: [
      "south",
      "south-west",
      "west",
      "north-west",
      "north",
      "north-east",
      "east",
      "south-east",
    ],
    asymmetric: true,
    hasHeldItems: false,
    runtimeEquipmentSwaps: true,
    runtimeCostumeVariants: true,
    independentEffects: true,
    independentShadow: true,
    needsCollision: true,
    needsNormalMap: false,
    needsEmissionMap: false,
    largeDeformations: true,
    secondaryMotion: ["equipment"],
    tileFootprint: { width: 1, height: 1 },
    notes: [
      "Author direction masters before in-between frames.",
      "Do not mirror east and west because coat fastenings and equipment are asymmetric.",
    ],
  },
  outputProfileIds: ["godot-4.6.2-isometric-character"],
  layerOverrides: [
    {
      role: "shadow",
      treatment: "linked-cel",
      reason:
        "Retain one registered cast-shadow family where the pose permits linked reuse; unlink only when the footprint genuinely changes.",
    },
    {
      role: "collision",
      treatment: "engine-sidecar",
      reason:
        "Collision belongs in deterministic Godot metadata and must never be baked into visible colour artwork.",
    },
  ],
  metadata: {
    owner: "EVAVO Studio",
    releaseBoundary: "compile-only",
    intendedEngine: "Godot 4.6.2",
  },
} as const satisfies ArtDirectionCompileRequestInput;
