import type { ArtBrief } from "@evavo/art-contracts";

export const DEFAULT_ART_BRIEF: ArtBrief = {
  schemaVersion: "1.0",
  project: {
    projectName: "Godot 4.6.2 adventure art system",
    gameGenre: "1990s cinematic point-and-click adventure",
    engine: "Godot 4.6.2",
    audience: "PC and web players who value authentic period art direction",
    targets: [
      {
        kind: "godot-4.6.2",
        platform: "desktop and web",
        maximumTextureSize: 4096,
        powerOfTwo: "preferred",
        textureFiltering: "nearest",
        compressionPolicy: "lossless",
        notes: [
          "Preserve pixel edges",
          "Export exact-duration SpriteFrames resources and atlas metadata",
        ],
      },
      { kind: "source-master", compressionPolicy: "lossless" },
    ],
  },
  artDirection: {
    styleName: "Authored 1990s game illustration",
    intent:
      "Deliberate human-directed shapes, silhouettes, material decisions and animation timing rather than generic model defaults.",
    era: "1990s PC and console production discipline",
    mustHave: [
      "strong readable silhouettes",
      "consistent character proportions",
      "clean production-ready transparency",
      "cohesive environment and interface language",
      "stable costume, equipment and handedness across frames",
    ],
    mustAvoid: [
      "generic AI composition",
      "fake checkerboard transparency",
      "edge halos",
      "uncontrolled detail noise",
      "inconsistent animation anchors",
      "independently reinvented frames",
      "cropped limbs, weapons, shadows or effect trails",
    ],
    palette: {
      colours: ["#070707", "#f4f4f0", "#ff244e", "#7b5b3b", "#41545f"],
      maxColours: 32,
      colourSpace: "srgb",
    },
    cameraRules: [
      "stage scenes for gameplay readability",
      "keep interaction lanes clear",
      "avoid accidental perspective changes between related backgrounds",
    ],
    lineTreatment:
      "Purposeful low-resolution clusters with hand-directed edges and no model-noise texture.",
  },
  assets: [
    {
      id: "hero-idle",
      name: "Hero idle animation",
      kind: "sprite-sheet",
      purpose: "Canonical controllable character identity and idle loop",
      quantity: 1,
      dimensions: { width: 96, height: 128 },
      transparency: "alpha-required",
      animation: {
        name: "idle",
        frameCount: 8,
        framesPerSecond: 8,
        loop: true,
        loopMode: "linear",
        directions: 4,
        directionNames: ["down", "left", "right", "up"],
        frameDurationsMs: [150, 100, 100, 100, 150, 100, 100, 100],
        keyPoseFrames: [0, 2, 4, 6],
        frameOrder: "direction-major",
        pivot: { x: 48, y: 118 },
        baseline: 118,
        motionNotes: [
          "keep both feet registered to the shared baseline",
          "move breathing through torso and coat without changing anatomy",
        ],
      },
      sprite: {
        productionMethod: "hybrid",
        layers: [
          {
            id: "body",
            role: "body",
            treatment: "baked-into-cel",
            zIndex: 10,
            reason:
              "Anatomy, coat folds, hands and authored pixel clusters must remain coherent cels without puppet seams.",
          },
          {
            id: "shadow",
            role: "shadow",
            treatment: "linked-cel",
            zIndex: 0,
            framePolicy: "linked-until-change",
            exportPolicy: "layer-frames",
            allowEmpty: true,
            reason:
              "The contact shadow is reusable and needs independent opacity and ground registration.",
          },
          {
            id: "held-item",
            role: "held-item",
            treatment: "separate-frame",
            parentId: "body",
            zIndex: 20,
            framePolicy: "every-frame",
            exportPolicy: "layer-frames",
            interchangeable: true,
            allowEmpty: true,
            reason:
              "Held objects are gameplay variants and must preserve attachment points without repainting the approved body.",
          },
        ],
        shot: {
          include: [
            "the complete hero silhouette and all declared costume details",
            "the complete held item when enabled",
            "the contact shadow inside the safe bounds",
          ],
          exclude: [
            "environment scenery and decorative backgrounds",
            "checkerboards, chroma mattes and labels",
            "unrelated props, particles and interface elements",
            "collision, normal and guide data in visible colour",
          ],
          safePadding: 6,
          backgroundPolicy: "transparent",
          allowCrop: false,
          shadowPolicy: "separate",
        },
        continuityLocks: [
          "identity",
          "proportions",
          "silhouette-language",
          "palette",
          "line-treatment",
          "camera",
          "pivot",
          "baseline",
          "ground-contact",
          "equipment",
          "handedness",
          "materials",
        ],
        allowedChanges: [
          "declared idle pose movement",
          "coat and hair secondary motion",
          "approved expression changes",
          "held-item visibility and registered occlusion",
        ],
        generation: {
          identityReferenceWeight: 0.94,
          structureReferenceWeight: 0.9,
          previousFrameWeight: 0.75,
          nextFrameWeight: 0.75,
          seedPolicy: "family-derived",
          requestUnit: "single-frame",
          allowIndependentTextOnlyFrames: false,
          structuralControls: ["pose-map", "silhouette-mask", "edge-map"],
        },
        source: {
          editableSource: "aseprite",
          retainIndividualFrames: true,
          retainLayerFrames: true,
          retainPackedDerivative: true,
          retainLinkedCels: true,
        },
      },
      outputs: [
        {
          format: "png",
          purpose: "runtime",
          lossless: true,
          colourSpace: "srgb",
        },
        {
          format: "webp",
          purpose: "preview",
          lossless: true,
          colourSpace: "srgb",
        },
        { format: "json", purpose: "manifest", lossless: true },
      ],
      tags: ["character", "four-direction", "pixel-art"],
      namingPrefix: "hero_idle",
    },
    {
      id: "hero-walk",
      name: "Hero walk animation",
      kind: "sprite-sheet",
      purpose: "Walk cycle inherited from the approved hero identity",
      quantity: 1,
      dimensions: { width: 96, height: 128 },
      transparency: "alpha-required",
      animation: {
        name: "walk",
        frameCount: 8,
        framesPerSecond: 10,
        loop: true,
        loopMode: "linear",
        directions: 4,
        directionNames: ["down", "left", "right", "up"],
        keyPoseFrames: [0, 2, 4, 6],
        frameOrder: "direction-major",
        pivot: { x: 48, y: 118 },
        baseline: 118,
      },
      sprite: {
        canonicalAssetId: "hero-idle",
        canonicalInstancePolicy: "shared",
        productionMethod: "authored-cel",
        allowedChanges: [
          "walk pose and weight shift",
          "coat and hair secondary motion",
          "declared held-item visibility",
        ],
        source: {
          editableSource: "aseprite",
          retainIndividualFrames: true,
          retainLayerFrames: false,
          retainPackedDerivative: true,
          retainLinkedCels: true,
        },
      },
      outputs: [
        {
          format: "png",
          purpose: "runtime",
          lossless: true,
          colourSpace: "srgb",
        },
        { format: "json", purpose: "manifest", lossless: true },
      ],
      tags: ["character", "four-direction", "pixel-art"],
      namingPrefix: "hero_walk",
    },
    {
      id: "rain-particles",
      name: "Rain particle family",
      kind: "particle",
      purpose: "Layered weather particles for foreground and background rain",
      quantity: 3,
      dimensions: { width: 32, height: 64 },
      transparency: "alpha-required",
      animation: {
        name: "fall",
        frameCount: 6,
        framesPerSecond: 12,
        loop: true,
        loopMode: "linear",
        keyPoseFrames: [0, 3],
        pivot: { x: 16, y: 32 },
      },
      sprite: {
        productionMethod: "authored-cel",
        shot: {
          safePadding: 2,
          backgroundPolicy: "transparent",
          allowCrop: false,
          shadowPolicy: "none",
        },
        continuityLocks: [
          "silhouette-language",
          "palette",
          "line-treatment",
          "pivot",
        ],
        allowedChanges: [
          "streak length",
          "droplet breakup",
          "declared frame-to-frame particle deformation",
        ],
      },
      outputs: [
        {
          format: "png",
          purpose: "runtime",
          lossless: true,
          colourSpace: "srgb",
        },
        { format: "json", purpose: "manifest", lossless: true },
      ],
      namingPrefix: "weather_rain",
    },
  ],
  autonomy: {
    mode: "review-gated",
    candidateCount: 6,
    maximumIterations: 4,
    autoApproveThreshold: 0.95,
    allowProviderFallback: true,
    requireEvidenceBundle: true,
  },
  outputRoot: "art-production",
};
