import type { BookNarrativeArchetypeV1 } from "./book-studio-narrative-craft-types";

const dimensions = (values: Array<[BookNarrativeArchetypeV1["dimensionValues"][number]["dimensionId"], number]>): BookNarrativeArchetypeV1["dimensionValues"] => values.map(([dimensionId, value]) => ({ dimensionId, value }));

export const BOOK_NARRATIVE_ARCHETYPES: readonly BookNarrativeArchetypeV1[] = Object.freeze([
  { archetypeId: "ordinary_dread_escalation", dimensionValues: dimensions([["narrative_distance", -0.55], ["causal_density", 0.45], ["puzzle_density", 0.05], ["suspense_pressure", 0.75], ["ensemble_breadth", -0.15], ["prose_ornament", -0.1], ["dialogue_indirection", 0.35], ["dread_escalation", 0.9], ["audience_accessibility", 0.35], ["temporal_complexity", -0.2]]), productionBiases: ["Begin with credible ordinary pressure and let consequence expose deeper threat.", "Keep dread attached to concrete places, routines and relationships."], counterweights: ["Do not substitute grotesque escalation for causality.", "Do not make every perception ominous."] },
  { archetypeId: "puzzle_propulsion", dimensionValues: dimensions([["narrative_distance", -0.15], ["causal_density", 0.7], ["puzzle_density", 0.95], ["suspense_pressure", 0.65], ["ensemble_breadth", 0.05], ["prose_ornament", -0.45], ["dialogue_indirection", -0.1], ["dread_escalation", 0.15], ["audience_accessibility", 0.7], ["temporal_complexity", 0.2]]), productionBiases: ["Convert each answer into a more consequential question.", "Use clear spatial and causal sequencing under time pressure."], counterweights: ["Do not let explanation replace character cost.", "Do not hide evidence unfairly."] },
  { archetypeId: "dynastic_causality", dimensionValues: dimensions([["narrative_distance", 0.15], ["causal_density", 0.9], ["puzzle_density", 0.25], ["suspense_pressure", 0.45], ["ensemble_breadth", 0.85], ["prose_ornament", 0.25], ["dialogue_indirection", 0.65], ["dread_escalation", 0.25], ["audience_accessibility", 0.05], ["temporal_complexity", 0.55]]), productionBiases: ["Let private choices propagate through institutions, families and factions.", "Make status, obligation and memory shape dialogue."], counterweights: ["Do not confuse cast size with depth.", "Do not resolve politics through unexplained omniscience."] },
  { archetypeId: "submerged_minimalism", dimensionValues: dimensions([["narrative_distance", -0.35], ["causal_density", 0.55], ["puzzle_density", -0.2], ["suspense_pressure", 0.1], ["ensemble_breadth", -0.45], ["prose_ornament", -0.9], ["dialogue_indirection", 0.8], ["dread_escalation", -0.05], ["audience_accessibility", 0.35], ["temporal_complexity", -0.4]]), productionBiases: ["Place emotional weight beneath plain action and selective detail.", "Let omission be legible through context, not vagueness."], counterweights: ["Do not remove necessary causal or emotional evidence.", "Do not mistake short sentences for precision."] },
  { archetypeId: "youth_horror_escalation", dimensionValues: dimensions([["narrative_distance", -0.65], ["causal_density", 0.25], ["puzzle_density", 0.45], ["suspense_pressure", 0.8], ["ensemble_breadth", -0.25], ["prose_ornament", -0.55], ["dialogue_indirection", -0.25], ["dread_escalation", 0.85], ["audience_accessibility", 0.95], ["temporal_complexity", -0.55]]), productionBiases: ["Use immediate concrete stakes and progressive rule discovery.", "Keep syntax accessible without simplifying emotion or consequence."], counterweights: ["Do not rely on repetitive cliff-hangers.", "Do not make young characters emotionally generic."] },
  { archetypeId: "epic_ensemble_continuity", dimensionValues: dimensions([["narrative_distance", 0.3], ["causal_density", 0.75], ["puzzle_density", 0.2], ["suspense_pressure", 0.35], ["ensemble_breadth", 0.95], ["prose_ornament", 0.35], ["dialogue_indirection", 0.45], ["dread_escalation", 0.1], ["audience_accessibility", 0.15], ["temporal_complexity", 0.5]]), productionBiases: ["Balance intimate motives with long causal chains across an ensemble.", "Preserve geography, capability, obligation and relationship continuity."], counterweights: ["Do not solve scale by summarising away decisive scenes.", "Do not flatten secondary characters into faction labels."] },
  { archetypeId: "time_braided_cosmic_intimacy", dimensionValues: dimensions([["narrative_distance", 0.05], ["causal_density", 0.4], ["puzzle_density", 0.55], ["suspense_pressure", 0.35], ["ensemble_breadth", 0.55], ["prose_ornament", 0.75], ["dialogue_indirection", 0.5], ["dread_escalation", 0.3], ["audience_accessibility", -0.15], ["temporal_complexity", 0.95]]), productionBiases: ["Use large temporal or conceptual scale to intensify personal loss, choice and memory.", "Make structural complexity yield emotional and causal payoff."], counterweights: ["Do not let abstraction replace sensory and relational anchors.", "Do not confuse obscurity with profundity."] },
  { archetypeId: "intimate_social_realism", dimensionValues: dimensions([["narrative_distance", -0.75], ["causal_density", 0.65], ["puzzle_density", -0.4], ["suspense_pressure", 0.05], ["ensemble_breadth", 0.15], ["prose_ornament", -0.15], ["dialogue_indirection", 0.75], ["dread_escalation", -0.2], ["audience_accessibility", 0.45], ["temporal_complexity", -0.15]]), productionBiases: ["Build pressure from ordinary obligations, social reading and accumulated relationship history.", "Let small choices produce durable interpersonal consequences."], counterweights: ["Do not equate realism with inactivity.", "Do not explain every social cue."] },
]);
