import type { BookNarrativeQualityCriterionV1, BookNarrativeRevisionStepV1 } from "./book-studio-narrative-craft-types";

export const BOOK_NARRATIVE_QUALITY_RUBRIC: readonly BookNarrativeQualityCriterionV1[] = Object.freeze([
  { criterionId: "causal_necessity", weight: 10, mandatory: true, passCondition: "The scene changes later possibility through action, discovery, error or refusal.", failureSignals: ["removable scene", "coincidental turn", "reset ending"] },
  { criterionId: "character_appraisal", weight: 10, mandatory: true, passCondition: "Each important reaction follows character-specific goals, beliefs, knowledge and relationship pressure.", failureSignals: ["generic reaction", "knowledge leak", "unearned reversal"] },
  { criterionId: "emotion_regulation_trace", weight: 8, mandatory: true, passCondition: "Trigger, appraisal, action tendency, regulation, display and aftereffect form a plausible sequence.", failureSignals: ["emotion label only", "instant recovery", "suppression without cost"] },
  { criterionId: "dialogue_responsiveness", weight: 8, mandatory: false, passCondition: "Every turn responds to prior action and changes common ground, commitment or leverage.", failureSignals: ["reorderable lines", "parallel monologues", "decorative interruption"] },
  { criterionId: "dialogue_subtext_status", weight: 8, mandatory: false, passCondition: "Literal speech, private objective, face risk and status pressure remain distinguishable.", failureSignals: ["everyone says exactly what they mean", "status-free exchange", "vague subtext"] },
  { criterionId: "voice_distinctness", weight: 8, mandatory: true, passCondition: "Syntax, lexicon, timing, taboo and indirectness arise from character and relationship rather than gimmicks.", failureSignals: ["interchangeable voices", "catchphrase-only voice", "accent caricature"] },
  { criterionId: "viewpoint_integrity", weight: 8, mandatory: true, passCondition: "Perception, inference and psychic access remain inside the declared viewpoint boundary.", failureSignals: ["head hop", "neutral inventory", "premature inference"] },
  { criterionId: "concrete_specificity", weight: 8, mandatory: true, passCondition: "Selected objects, actions and sensory details reveal pressure, causality, viewpoint or motif.", failureSignals: ["generic intensifiers", "decorative sensory list", "abstract emotion summary"] },
  { criterionId: "sentence_paragraph_rhythm", weight: 6, mandatory: false, passCondition: "Cadence and paragraph shape follow attention, action, hesitation, turn and release.", failureSignals: ["uniform cadence", "random sentence variation", "identical paragraph blocks"] },
  { criterionId: "tension_information_release", weight: 7, mandatory: false, passCondition: "Suspense, curiosity or surprise follows fair information control and changes decisions.", failureSignals: ["arbitrary withholding", "unsupported reveal", "question pile-up"] },
  { criterionId: "relationship_memory", weight: 6, mandatory: true, passCondition: "Prior promises, harms, favours, debts and repairs alter present interpretation and choice.", failureSignals: ["relationship reset", "costless betrayal", "identical social models"] },
  { criterionId: "anti_genericity", weight: 7, mandatory: true, passCondition: "Language and behaviour are specific to this project, speaker, place and moment.", failureSignals: ["stock gesture", "formulaic contrast", "transferable scene"] },
  { criterionId: "project_voice_originality", weight: 4, mandatory: true, passCondition: "Project-owned voice anchors control expression and no source creator is reconstructed.", failureSignals: ["named-source cue", "single-source resemblance", "voice-anchor drift"] },
  { criterionId: "rights_safety", weight: 2, mandatory: true, passCondition: "No named-author imitation, distinctive surface transfer or unauthorised phrase reuse appears.", failureSignals: ["imitation instruction", "distinctive reconstruction", "blocking phrase overlap"] },
]);

export const BOOK_NARRATIVE_REVISION_PROTOCOL: readonly BookNarrativeRevisionStepV1[] = Object.freeze([
  { sequence: 1, stepId: "causal_spine", instruction: "Verify objective, opposition, tactic, turn, outcome, cost and downstream consequence before polishing sentences.", requiredEvidenceKinds: ["scene-state", "causal-link"] },
  { sequence: 2, stepId: "character_appraisal", instruction: "Reconstruct each important reaction from values, beliefs, knowledge, misbelief, agency and relationship pressure.", requiredEvidenceKinds: ["character-state", "knowledge-state"] },
  { sequence: 3, stepId: "emotion_regulation", instruction: "Trace trigger through attention, appraisal, action tendency, regulation, display and delayed aftereffect.", requiredEvidenceKinds: ["emotion-beat", "regulation-choice"] },
  { sequence: 4, stepId: "dialogue_turn_map", instruction: "Map every turn to the prior turn, conversational objective and resulting common-ground update.", requiredEvidenceKinds: ["turn-function", "common-ground"] },
  { sequence: 5, stepId: "subtext_status_repair", instruction: "Test concealment, face risk, status permissions, misunderstanding and repair opportunities.", requiredEvidenceKinds: ["status-risk", "repair-state"] },
  { sequence: 6, stepId: "viewpoint_filter", instruction: "Remove perception, inference, language and psychic access that the focal viewpoint cannot support.", requiredEvidenceKinds: ["viewpoint-boundary", "knowledge-source"] },
  { sequence: 7, stepId: "specificity_rhythm", instruction: "Replace generic summary with selective concrete evidence and shape cadence around attention and action.", requiredEvidenceKinds: ["prose-anchor", "rhythm-pass"] },
  { sequence: 8, stepId: "tension_reveal", instruction: "Verify fair setup, uncertainty, reveal order, retrospective coherence and decision-changing payoff.", requiredEvidenceKinds: ["setup", "payoff", "information-state"] },
  { sequence: 9, stepId: "originality_assurance", instruction: "Remove stock patterns, run phrase-overlap assurance and require independent review before admission.", requiredEvidenceKinds: ["anti-genericity", "phrase-overlap", "independent-review"] },
]);
