#!/usr/bin/env node
import { createHash } from "node:crypto";
import { access, lstat, readFile, realpath } from "node:fs/promises";
import { delimiter, extname, isAbsolute, relative, resolve } from "node:path";
import process from "node:process";
import readline from "node:readline";
import { pathToFileURL } from "node:url";

export const PROTOCOL_VERSION="2026-09-01.1";
export const MANIFEST_SCHEMA="evavo.animation-character-family-campaign-adapters.v1";
export const REPORT_SCHEMA="evavo.animation-character-family-campaign-preflight.report.v1";
const TASKS=["produce-clip","repair-clip","repair-transition","repair-family","review-family"];
const ROLE_TASKS={"art-studio":TASKS.slice(0,4),"cel-animation-studio":["review-family"],coordinator:TASKS};
const OWNERS={"produce-clip":"art-studio","repair-clip":"art-studio","repair-transition":"art-studio","repair-family":"art-studio","review-family":"cel-animation-studio"};
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,191}$/u, DIGEST=/^sha256:[0-9a-f]{64}$/u, ENV=/^[A-Z_][A-Z0-9_]{0,127}$/u;
const SHELL=new Set(["cmd","cmd.exe","powershell","powershell.exe","pwsh","pwsh.exe","sh","bash","zsh","fish"]);
const SWITCH=new Set(["-c","/c","-command","-encodedcommand"]);
const CODE=new Set([".js",".cjs",".mjs",".ts",".cts",".mts",".py",".ps1",".sh"]);
const CRED_KEY=/(?:api[_-]?key|access[_-]?token|refresh[_-]?token|password|passwd|secret|authorization|cookie|private[_-]?key)/iu;
const CRED_VALUE=/(?:bearer\s+[A-Za-z0-9._~+/-]{12,}|-----BEGIN [A-Z ]*PRIVATE KEY-----)/iu;
const AUTH=Object.freeze({providerExecution:false,localExecution:false,automaticCreativeApproval:false,creativeApproval:false,artifactPromotion:false,repositoryMutation:false,gitCommit:false,gitPush:false,runtimeActivation:false,publication:false,deployment:false});

function fail(code,detail=""){throw new Error(detail?`${code}:${detail}`:code);}
function obj(v,c){if(!v||typeof v!=="object"||Array.isArray(v))fail(c);return v;}
function arr(v,c){if(!Array.isArray(v))fail(c);return v;}
function id(v,c){if(typeof v!=="string"||!ID.test(v))fail(c);return v;}
function digest(v,c){if(typeof v!=="string"||!DIGEST.test(v))fail(c);return v;}
function integer(v,a,b,c){if(!Number.isSafeInteger(v)||v<a||v>b)fail(c);return v;}
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canonical(x)]));return v;}
export function sha256(v){const b=Buffer.isBuffer(v)?v:typeof v==="string"?Buffer.from(v):Buffer.from(JSON.stringify(canonical(v)));return`sha256:${createHash("sha256").update(b).digest("hex")}`;}
function body(v,k){const x=structuredClone(v);delete x[k];return x;}
function inside(r,p){const x=relative(r,p);return x===""||(!x.startsWith("..")&&!isAbsolute(x));}
function rel(v,c){if(typeof v!=="string"||!v.trim()||v.includes("\0")||isAbsolute(v)||/^[A-Za-z]:[\\/]/u.test(v)||v.startsWith("\\\\"))fail(c);const n=v.replaceAll("\\","/");if(n.startsWith("/")||n.includes("//")||n.split("/").some(x=>!x||x==="."||x===".."))fail(c);return n;}
function scan(v,p="$"){if(Array.isArray(v)){v.forEach((x,i)=>scan(x,`${p}[${i}]`));return;}if(v&&typeof v==="object"){for(const[k,x]of Object.entries(v)){if(CRED_KEY.test(k))fail("ANIMATION_FAMILY_PREFLIGHT_CREDENTIAL_KEY_FORBIDDEN",`${p}.${k}`);scan(x,`${p}.${k}`);}return;}if(typeof v==="string"&&CRED_VALUE.test(v))fail("ANIMATION_FAMILY_PREFLIGHT_CREDENTIAL_VALUE_FORBIDDEN",p);}
function validateManifest(v){const m=obj(v,"ANIMATION_FAMILY_PREFLIGHT_MANIFEST_INVALID");if(m.schema!==MANIFEST_SCHEMA||m.protocolVersion!==PROTOCOL_VERSION)fail("ANIMATION_FAMILY_PREFLIGHT_MANIFEST_SCHEMA_INVALID");id(m.manifestId,"ANIMATION_FAMILY_PREFLIGHT_MANIFEST_ID_INVALID");id(m.campaignId,"ANIMATION_FAMILY_PREFLIGHT_CAMPAIGN_ID_INVALID");digest(m.familyPlanDigest,"ANIMATION_FAMILY_PREFLIGHT_FAMILY_DIGEST_INVALID");const ids=new Set();for(const a of arr(m.adapters,"ANIMATION_FAMILY_PREFLIGHT_ADAPTERS_INVALID")){id(a.adapterId,"ANIMATION_FAMILY_PREFLIGHT_ADAPTER_ID_INVALID");if(ids.has(a.adapterId))fail("ANIMATION_FAMILY_PREFLIGHT_ADAPTER_ID_DUPLICATE",a.adapterId);ids.add(a.adapterId);if(!["art-studio","cel-animation-studio"].includes(a.ownerRole))fail("ANIMATION_FAMILY_PREFLIGHT_ADAPTER_OWNER_INVALID",a.adapterId);if(!["command","module"].includes(a.kind)||typeof a.enabled!=="boolean")fail("ANIMATION_FAMILY_PREFLIGHT_ADAPTER_KIND_INVALID",a.adapterId);const kinds=arr(a.taskKinds,"ANIMATION_FAMILY_PREFLIGHT_TASK_KINDS_INVALID");if(!kinds.length||new Set(kinds).size!==kinds.length)fail("ANIMATION_FAMILY_PREFLIGHT_TASK_KINDS_INVALID",a.adapterId);for(const k of kinds){if(!TASKS.includes(k))fail("ANIMATION_FAMILY_PREFLIGHT_TASK_KIND_UNKNOWN",k);if(OWNERS[k]!==a.ownerRole)fail("ANIMATION_FAMILY_PREFLIGHT_TASK_OWNER_MISMATCH",`${a.adapterId}:${k}`);}id(a.rootId,"ANIMATION_FAMILY_PREFLIGHT_ROOT_ID_INVALID");rel(a.workingDirectory,"ANIMATION_FAMILY_PREFLIGHT_WORKING_DIRECTORY_INVALID");rel(a.entrypoint,"ANIMATION_FAMILY_PREFLIGHT_ENTRYPOINT_INVALID");integer(a.timeoutMs,100,3600000,"ANIMATION_FAMILY_PREFLIGHT_TIMEOUT_INVALID");integer(a.maximumOutputBytes,1024,67108864,"ANIMATION_FAMILY_PREFLIGHT_OUTPUT_LIMIT_INVALID");if(a.implementationSha256!==undefined)digest(a.implementationSha256,"ANIMATION_FAMILY_PREFLIGHT_IMPLEMENTATION_DIGEST_INVALID");const cmd=arr(a.command,"ANIMATION_FAMILY_PREFLIGHT_COMMAND_INVALID");if(!cmd.length||cmd.length>32||cmd.some(x=>typeof x!=="string"||!x||x.includes("\0")||x.length>2048))fail("ANIMATION_FAMILY_PREFLIGHT_COMMAND_INVALID",a.adapterId);const base=cmd[0].replaceAll("\\","/").split("/").at(-1).toLowerCase();if(SHELL.has(base)&&cmd.slice(1,3).some(x=>SWITCH.has(x.toLowerCase())))fail("ANIMATION_FAMILY_PREFLIGHT_SHELL_COMMAND_FORBIDDEN",a.adapterId);if(cmd.some(x=>["&&","||","|",";",">","<"].includes(x)))fail("ANIMATION_FAMILY_PREFLIGHT_SHELL_OPERATOR_FORBIDDEN",a.adapterId);const env=arr(a.environmentVariables,"ANIMATION_FAMILY_PREFLIGHT_ENVIRONMENT_INVALID");if(new Set(env).size!==env.length||env.some(x=>typeof x!=="string"||!ENV.test(x)))fail("ANIMATION_FAMILY_PREFLIGHT_ENVIRONMENT_INVALID",a.adapterId);if(!["required","optional"].includes(a.environmentPolicy))fail("ANIMATION_FAMILY_PREFLIGHT_ENVIRONMENT_POLICY_INVALID",a.adapterId);const copy={...a,environmentVariables:undefined};scan(copy);}return m;}
async function file(root,path){const p=resolve(root,path);if(!inside(root,p))fail("ANIMATION_FAMILY_PREFLIGHT_PATH_ESCAPES_ROOT");try{const s=await lstat(p);if(!s.isFile()||s.isSymbolicLink())return{exists:true,safe:false};const physical=await realpath(p);if(!inside(root,physical))fail("ANIMATION_FAMILY_PREFLIGHT_PATH_ESCAPES_ROOT");const b=await readFile(physical);return{exists:true,safe:true,bytes:b.length,sha256:sha256(b)};}catch(e){if(e?.code==="ENOENT")return{exists:false,safe:false};throw e;}}
async function dir(root,path){const p=resolve(root,path);if(!inside(root,p))fail("ANIMATION_FAMILY_PREFLIGHT_PATH_ESCAPES_ROOT");try{const s=await lstat(p);if(!s.isDirectory()||s.isSymbolicLink())return{exists:true,safe:false};const physical=await realpath(p);if(!inside(root,physical))fail("ANIMATION_FAMILY_PREFLIGHT_PATH_ESCAPES_ROOT");return{exists:true,safe:true};}catch(e){if(e?.code==="ENOENT")return{exists:false,safe:false};throw e;}}
async function executable(cmd,wd){const x=cmd[0];if(x==="node"||x==="node.exe")return{available:true,identity:"node",source:"current-runtime",version:process.versions.node};if(isAbsolute(x)||x.includes("/")||x.includes("\\")){try{const s=await lstat(isAbsolute(x)?x:resolve(wd,x));return{available:s.isFile()&&!s.isSymbolicLink(),identity:x,source:"explicit-path"};}catch(e){if(e?.code==="ENOENT")return{available:false,identity:x,source:"explicit-path"};throw e;}}const exts=process.platform==="win32"?String(process.env.PATHEXT??".EXE;.CMD;.BAT;.COM").split(";"):[""];for(const d of String(process.env.PATH??"").split(delimiter).filter(Boolean))for(const e of exts)try{const p=resolve(d,`${x}${e}`);await access(p);const s=await lstat(p);if(s.isFile()&&!s.isSymbolicLink())return{available:true,identity:x,source:"path"};}catch{}return{available:false,identity:x,source:"path"};}
const finding=(code,severity,detail)=>Object.freeze({code,severity,...(detail===undefined?{}:{detail})});
async function inspect(a,roots,env){const findings=[];let entry=null,exe=null,missing=[];const configured=roots[a.rootId];if(typeof configured!=="string"||!isAbsolute(configured))findings.push(finding("ROOT_UNAVAILABLE","blocker",a.rootId));else{let root;try{root=await realpath(configured);}catch(e){if(e?.code==="ENOENT")findings.push(finding("ROOT_MISSING","blocker",a.rootId));else throw e;}if(root){const wd=await dir(root,a.workingDirectory);if(!wd.exists)findings.push(finding("WORKING_DIRECTORY_MISSING","blocker"));else if(!wd.safe)findings.push(finding("WORKING_DIRECTORY_UNSAFE","blocker"));entry=await file(root,a.entrypoint);if(!entry.exists)findings.push(finding("ENTRYPOINT_MISSING","blocker"));else if(!entry.safe)findings.push(finding("ENTRYPOINT_UNSAFE","blocker"));else{if(!CODE.has(extname(a.entrypoint).toLowerCase()))findings.push(finding("ENTRYPOINT_EXTENSION_UNRECOGNIZED","warning"));if(a.implementationSha256&&a.implementationSha256!==entry.sha256)findings.push(finding("IMPLEMENTATION_DIGEST_MISMATCH","blocker",{expected:a.implementationSha256,actual:entry.sha256}));}exe=await executable(a.command,resolve(root,a.workingDirectory));if(!exe.available)findings.push(finding("EXECUTABLE_UNAVAILABLE","blocker",exe.identity));}}missing=a.environmentVariables.filter(n=>env[n]===undefined||env[n]==="");if(missing.length)findings.push(finding("ENVIRONMENT_NAMES_MISSING",a.environmentPolicy==="required"?"blocker":"warning",missing));const blockers=findings.filter(x=>x.severity==="blocker").length,warnings=findings.filter(x=>x.severity==="warning").length;return Object.freeze({adapterId:a.adapterId,ownerRole:a.ownerRole,taskKinds:Object.freeze([...a.taskKinds].sort()),enabled:a.enabled,status:!a.enabled?"disabled":blockers?"blocked":warnings?"partial":"ready",rootId:a.rootId,workingDirectory:a.workingDirectory,entrypoint:a.entrypoint,implementation:entry?.safe?Object.freeze({sha256:entry.sha256,byteLength:entry.bytes}):null,executable:exe,missingEnvironmentNames:Object.freeze([...missing].sort()),findings:Object.freeze(findings)});}
export async function compileAnimationCharacterFamilyCampaignPreflight(input){const s=obj(input,"ANIMATION_FAMILY_PREFLIGHT_INPUT_INVALID"),m=validateManifest(s.manifest),role=s.role??"coordinator";if(!ROLE_TASKS[role])fail("ANIMATION_FAMILY_PREFLIGHT_ROLE_INVALID",role);const roots=obj(s.repositoryRoots,"ANIMATION_FAMILY_PREFLIGHT_REPOSITORY_ROOTS_INVALID"),env=s.environment===undefined?process.env:obj(s.environment,"ANIMATION_FAMILY_PREFLIGHT_ENVIRONMENT_INVALID");for(const[k,v]of Object.entries(roots)){id(k,"ANIMATION_FAMILY_PREFLIGHT_ROOT_KEY_INVALID");if(typeof v!=="string"||!isAbsolute(v))fail("ANIMATION_FAMILY_PREFLIGHT_ROOT_PATH_INVALID",k);}const observations=[];for(const a of m.adapters)observations.push(await inspect(a,roots,env));observations.sort((a,b)=>a.adapterId.localeCompare(b.adapterId));const required=[...ROLE_TASKS[role]],coverage=required.map(taskKind=>{const candidates=observations.filter(x=>x.enabled&&x.taskKinds.includes(taskKind)),ready=candidates.filter(x=>x.status==="ready"),partial=candidates.filter(x=>x.status==="partial"),blocked=candidates.filter(x=>x.status==="blocked");return Object.freeze({taskKind,ownerRole:OWNERS[taskKind],status:ready.length?"ready":partial.length?"partial":"blocked",readyAdapterIds:Object.freeze(ready.map(x=>x.adapterId)),partialAdapterIds:Object.freeze(partial.map(x=>x.adapterId)),blockedAdapterIds:Object.freeze(blocked.map(x=>x.adapterId))});}),status=coverage.some(x=>x.status==="blocked")?"blocked":coverage.some(x=>x.status==="partial")?"partial":"ready",nextActions=coverage.filter(x=>x.status!=="ready").map(x=>Object.freeze({action:x.status==="blocked"?"provide-ready-adapter":"resolve-adapter-warning",taskKind:x.taskKind,ownerRole:x.ownerRole,adapterIds:x.status==="partial"?x.partialAdapterIds:undefined})),b={schema:REPORT_SCHEMA,protocolVersion:PROTOCOL_VERSION,reportId:id(s.reportId,"ANIMATION_FAMILY_PREFLIGHT_REPORT_ID_INVALID"),role,manifestId:m.manifestId,manifestDigest:sha256(m),campaignId:m.campaignId,familyPlanDigest:m.familyPlanDigest,status,requiredTasks:Object.freeze(required),adapterObservations:Object.freeze(observations),taskCoverage:Object.freeze(coverage),nextActions:Object.freeze(nextActions),authority:AUTH};return Object.freeze({...b,reportDigest:sha256(b)});}
export function verifyAnimationCharacterFamilyCampaignPreflight(v){const r=obj(v,"ANIMATION_FAMILY_PREFLIGHT_REPORT_INVALID");if(r.schema!==REPORT_SCHEMA||r.protocolVersion!==PROTOCOL_VERSION)fail("ANIMATION_FAMILY_PREFLIGHT_REPORT_SCHEMA_INVALID");digest(r.reportDigest,"ANIMATION_FAMILY_PREFLIGHT_REPORT_DIGEST_INVALID");if(sha256(body(r,"reportDigest"))!==r.reportDigest)fail("ANIMATION_FAMILY_PREFLIGHT_REPORT_DIGEST_MISMATCH");if(Object.keys(r.authority??{}).length!==11||Object.values(r.authority).some(x=>x!==false))fail("ANIMATION_FAMILY_PREFLIGHT_AUTHORITY_INVALID");const b={schema:"evavo.animation-character-family-campaign-preflight.verification.v1",protocolVersion:PROTOCOL_VERSION,reportId:r.reportId,reportDigest:r.reportDigest,status:"verified",authority:AUTH};return Object.freeze({...b,verificationDigest:sha256(b)});}
export function describeAnimationCharacterFamilyCampaignPreflight(){return Object.freeze({schema:"evavo.animation-character-family-campaign-preflight.description.v1",protocolVersion:PROTOCOL_VERSION,manifestSchema:MANIFEST_SCHEMA,reportSchema:REPORT_SCHEMA,taskKinds:TASKS,roleTasks:ROLE_TASKS,taskOwners:OWNERS,readsLocalFilesystem:true,executesAdapters:false,authority:AUTH});}
async function readJson(p){const b=await readFile(resolve(p));if(b.length>16*1024*1024)fail("ANIMATION_FAMILY_PREFLIGHT_CLI_INPUT_TOO_LARGE");return JSON.parse(b);}
async function cli(args){const[c,p]=args;if(c==="describe"){console.log(JSON.stringify(describeAnimationCharacterFamilyCampaignPreflight(),null,2));return;}if(c==="mcp"){serveMcp();return;}if(!p)fail("ANIMATION_FAMILY_PREFLIGHT_CLI_INPUT_REQUIRED");const v=await readJson(p),o=c==="inspect"?await compileAnimationCharacterFamilyCampaignPreflight(v):c==="verify"?verifyAnimationCharacterFamilyCampaignPreflight(v):fail("ANIMATION_FAMILY_PREFLIGHT_CLI_COMMAND_INVALID",c);console.log(JSON.stringify(o,null,2));}
function serveMcp(){const enabled=process.env.EVAVO_ANIMATION_CHARACTER_FAMILY_PREFLIGHT_READ_ENABLED==="enabled",tools=()=>[{name:"describe_animation_character_family_campaign_preflight_v1",description:"Describe the read-only campaign adapter preflight.",inputSchema:{type:"object",additionalProperties:false}},{name:"verify_animation_character_family_campaign_preflight_v1",description:"Verify a content-addressed preflight report.",inputSchema:{type:"object",required:["report"],properties:{report:{type:"object"}},additionalProperties:false}},...(enabled?[{name:"inspect_animation_character_family_campaign_adapters_v1",description:"Read local adapter roots and compile readiness without executing adapters.",inputSchema:{type:"object",required:["reportId","role","manifest","repositoryRoots"],properties:{reportId:{type:"string"},role:{enum:["art-studio","cel-animation-studio","coordinator"]},manifest:{type:"object"},repositoryRoots:{type:"object"},environment:{type:"object"}},additionalProperties:false}}]:[])];const ok=(id,result)=>console.log(JSON.stringify({jsonrpc:"2.0",id,result})),bad=(id,e)=>console.log(JSON.stringify({jsonrpc:"2.0",id:id??null,error:{code:-32000,message:e instanceof Error?e.message:String(e)}}));const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});rl.on("line",line=>{let m;try{if(Buffer.byteLength(line)>4*1024*1024)fail("ANIMATION_FAMILY_PREFLIGHT_MCP_MESSAGE_TOO_LARGE");m=JSON.parse(line);if(m.method==="notifications/initialized")return;if(m.method==="initialize")return ok(m.id,{protocolVersion:m.params?.protocolVersion??"2025-06-18",capabilities:{tools:{listChanged:false}},serverInfo:{name:"evavo-animation-character-family-campaign-preflight-v1",version:"1.0.0"}});if(m.method==="ping")return ok(m.id,{});if(m.method==="tools/list")return ok(m.id,{tools:tools()});if(m.method==="tools/call"){const n=m.params?.name,a=m.params?.arguments??{};const promise=n==="describe_animation_character_family_campaign_preflight_v1"?Promise.resolve({...describeAnimationCharacterFamilyCampaignPreflight(),localReadEnabled:enabled}):n==="verify_animation_character_family_campaign_preflight_v1"?Promise.resolve(verifyAnimationCharacterFamilyCampaignPreflight(a.report)):n==="inspect_animation_character_family_campaign_adapters_v1"&&enabled?compileAnimationCharacterFamilyCampaignPreflight(a):Promise.reject(new Error("ANIMATION_FAMILY_PREFLIGHT_MCP_TOOL_UNKNOWN"));promise.then(v=>ok(m.id,{content:[{type:"text",text:JSON.stringify(v,null,2)}],structuredContent:v,isError:false})).catch(e=>bad(m.id,e));return;}fail("ANIMATION_FAMILY_PREFLIGHT_MCP_METHOD_UNKNOWN");}catch(e){bad(m?.id,e);}});}
if((process.argv[1]?pathToFileURL(resolve(process.argv[1])).href:"")===import.meta.url)cli(process.argv.slice(2)).catch(e=>{console.error(JSON.stringify({status:"error",message:e instanceof Error?e.message:String(e)}));process.exitCode=1;});
