#!/usr/bin/env node
import { lstatSync,realpathSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { createInterface } from 'node:readline';
import { ACTIONS,authority,compileRawArtSessionPlan,inventorySummary,materializeRawArtSession,scanRawArtFolder,verifyRawArtSession,writeJsonCreateOnly } from '../scripts/raw-art-folder-workbench.mjs';
export const SERVER_NAME='evavo-raw-art-folder-workbench',SERVER_VERSION='1.0.0';
const bool=(v,f=false)=>{if(v==null||v==='')return f;const n=String(v).toLowerCase();if(['1','true','yes','on'].includes(n))return true;if(['0','false','no','off'].includes(n))return false;throw new Error('Boolean environment value is invalid.')};
function policy(env=process.env){const value=String(env.EVAVO_RAW_ART_FOLDER_MCP_MODE??'read-only').toLowerCase();if(!['read-only','read-write'].includes(value))throw new Error('EVAVO_RAW_ART_FOLDER_MCP_MODE must be read-only or read-write.');const writes=value==='read-write'&&bool(env.EVAVO_RAW_ART_FOLDER_MCP_ALLOW_WRITES);if(value==='read-write'&&!writes)throw new Error('read-write mode requires EVAVO_RAW_ART_FOLDER_MCP_ALLOW_WRITES=true.');return Object.freeze({value,writesEnabled:writes})}
function roots(env=process.env){const separator=process.platform==='win32'?';':':',values=String(env.EVAVO_RAW_ART_FOLDER_ALLOWED_ROOTS??'').split(separator).map(v=>v.trim()).filter(Boolean).map(v=>path.resolve(v));if(!values.length)throw new Error('EVAVO_RAW_ART_FOLDER_ALLOWED_ROOTS must not be empty.');return Object.freeze([...new Set(values)].map(lexical=>{const s=lstatSync(lexical);if(!s.isDirectory()||s.isSymbolicLink())throw new Error(`Allowed root is invalid: ${lexical}.`);const real=realpathSync(lexical);if(path.normalize(real)!==path.normalize(lexical))throw new Error(`Allowed root must be canonical: ${lexical}.`);return Object.freeze({lexical,real})}))}
const inside=(r,c)=>{const v=path.relative(r,c);return v===''||(v!=='..'&&!v.startsWith(`..${path.sep}`)&&!path.isAbsolute(v))};
function confined(value,label,current,{future=false}={}){if(typeof value!=='string'||!value.trim()||value.includes('\0'))throw new Error(`${label} is required.`);const requested=path.resolve(value);let existing=requested;for(;;){try{const s=lstatSync(existing);if(s.isSymbolicLink())throw new Error(`${label} contains a symbolic link.`);break}catch(e){if(!future||e?.code!=='ENOENT')throw e;const p=path.dirname(existing);if(p===existing)throw e;existing=p}}const real=realpathSync(existing);if(!current.some(r=>inside(r.real,real)&&inside(r.lexical,requested)))throw new Error(`${label} is outside allowed roots.`);return requested}
const object=(properties,required=[])=>({type:'object',additionalProperties:false,properties,...(required.length?{required}:{})}),p={type:'string',minLength:1,maxLength:32768},confirm={type:'boolean',const:true};
export function toolDefinitions(current=policy()){const tools=[{name:'evavo_raw_art_folder_capabilities',description:'Describe exact RAW_ART inventory, reviewed session, create-only materialisation and verification capabilities.',inputSchema:object({})},{name:'evavo_raw_art_folder_inspect',description:'Scan one exact RAW_ART folder without modifying it and return bounded duplicate, sequence, atlas and warning evidence.',inputSchema:object({rawArtRoot:p,maximumFiles:{type:'integer',minimum:1},maximumBytes:{type:'integer',minimum:1},sampleLimit:{type:'integer',minimum:0,maximum:200}},['rawArtRoot'])},{name:'evavo_raw_art_folder_verify_session',description:'Independently verify every declared file and hash in one materialised session.',inputSchema:object({sessionRoot:p},['sessionRoot'])}];if(current.writesEnabled)tools.push({name:'evavo_raw_art_folder_write_inventory',description:'Write one create-only exact RAW_ART inventory. Requires confirmWrite=true.',inputSchema:object({rawArtRoot:p,outputPath:p,generatedAt:{type:'string'},maximumFiles:{type:'integer'},maximumBytes:{type:'integer'},confirmWrite:confirm},['rawArtRoot','outputPath','confirmWrite'])},{name:'evavo_raw_art_folder_compile_session',description:'Compile owner-reviewed decisions into one create-only session plan. Requires confirmWrite=true.',inputSchema:object({inventoryPath:p,decisionsPath:p,outputPath:p,compiledAt:{type:'string'},confirmWrite:confirm},['inventoryPath','decisionsPath','outputPath','confirmWrite'])},{name:'evavo_raw_art_folder_materialize_session',description:'Materialise reviewed copies outside RAW_ART after exact source revalidation. Requires confirmWrite=true.',inputSchema:object({planPath:p,confirmWrite:confirm},['planPath','confirmWrite'])});return Object.freeze(tools)}
const envelope=(summary,effects={})=>Object.freeze({summary,effects:Object.freeze({inventoryWrite:effects.inventoryWrite===true,planWrite:effects.planWrite===true,sessionWrite:effects.sessionWrite===true,...authority}),bytesFlowThroughMcp:false,credentialsForwarded:false});
export async function callTool(name,input={},context={}){const current=context.policy??context.mode??policy(context.environment),allowed=context.roots??roots(context.environment);if(!toolDefinitions(current).some(t=>t.name===name))throw new Error(`Unknown or prohibited RAW_ART tool ${name}.`);if(name==='evavo_raw_art_folder_capabilities')return envelope({schema:'evavo.raw-art-folder-workbench-capabilities.v1',version:SERVER_VERSION,mode:current.value,writesEnabled:current.writesEnabled,allowedRootCount:allowed.length,actions:ACTIONS,tools:toolDefinitions(current).map(t=>t.name)});if(name==='evavo_raw_art_folder_inspect'){const value=await scanRawArtFolder({rawArtRoot:confined(input.rawArtRoot,'rawArtRoot',allowed),maximumFiles:input.maximumFiles,maximumBytes:input.maximumBytes});return envelope(inventorySummary(value,input.sampleLimit??25))}if(name==='evavo_raw_art_folder_verify_session')return envelope(await verifyRawArtSession({sessionRoot:confined(input.sessionRoot,'sessionRoot',allowed)}));if(input.confirmWrite!==true)throw new Error(`${name} requires confirmWrite=true.`);if(name==='evavo_raw_art_folder_write_inventory'){const value=await scanRawArtFolder({rawArtRoot:confined(input.rawArtRoot,'rawArtRoot',allowed),generatedAt:input.generatedAt,maximumFiles:input.maximumFiles,maximumBytes:input.maximumBytes}),outputPath=confined(input.outputPath,'outputPath',allowed,{future:true});await writeJsonCreateOnly(outputPath,value);return envelope({status:'written',outputPath,inventorySha256:value.inventorySha256,totals:value.totals},{inventoryWrite:true})}if(name==='evavo_raw_art_folder_compile_session'){const value=await compileRawArtSessionPlan({inventoryPath:confined(input.inventoryPath,'inventoryPath',allowed),decisionsPath:confined(input.decisionsPath,'decisionsPath',allowed),compiledAt:input.compiledAt}),outputPath=confined(input.outputPath,'outputPath',allowed,{future:true});await writeJsonCreateOnly(outputPath,value);return envelope({status:'planned',outputPath,planSha256:value.planSha256,sessionRoot:value.sessionRoot,operationCount:value.operations.length},{planWrite:true})}if(name==='evavo_raw_art_folder_materialize_session')return envelope(await materializeRawArtSession({planPath:confined(input.planPath,'planPath',allowed)}),{sessionWrite:true});throw new Error(`Unknown tool ${name}.`)}
const response=(id,result)=>({jsonrpc:'2.0',id:id??null,result}),content=v=>[{type:'text',text:JSON.stringify(v,null,2)}];
export async function handleRequest(request,context={}){if(request?.jsonrpc!=='2.0'||typeof request.method!=='string')throw new Error('Invalid JSON-RPC request.');const current=context.policy??context.mode??policy(context.environment);if(request.method==='initialize')return response(request.id,{protocolVersion:request.params?.protocolVersion??'2025-03-26',capabilities:{tools:{}},serverInfo:{name:SERVER_NAME,version:SERVER_VERSION},instructions:'RAW_ART originals are read-only. Session copies require explicit write gates and confirmWrite=true. Provider, approval, Storage, repository, Git and publication authorities remain separate.'});if(request.method==='ping')return response(request.id,{});if(request.method==='notifications/initialized')return null;if(request.method==='tools/list')return response(request.id,{tools:toolDefinitions(current)});if(request.method==='tools/call'){try{const value=await callTool(request.params?.name,request.params?.arguments??{},context);return response(request.id,{content:content(value),structuredContent:value,isError:false})}catch(e){return response(request.id,{content:content({code:e?.code??'RAW_ART_FOLDER_TOOL_REJECTED',message:e.message}),isError:true})}}throw new Error(`Unsupported MCP method ${request.method}.`)}
export async function startServer(options={}){const context={environment:options.environment??process.env,policy:options.policy,roots:options.roots},input=createInterface({input:process.stdin,crlfDelay:Infinity,terminal:false});for await(const line of input){if(!line.trim())continue;let request;try{request=JSON.parse(line);const result=await handleRequest(request,context);if(result)process.stdout.write(`${JSON.stringify(result)}\n`)}catch(e){process.stdout.write(`${JSON.stringify({jsonrpc:'2.0',id:request?.id??null,error:{code:-32000,message:e.message}})}\n`)}}}
const invoked=process.argv[1]&&path.resolve(process.argv[1])===path.resolve(new URL(import.meta.url).pathname);if(invoked)startServer().catch(e=>{process.stderr.write(`${e.stack??e.message}\n`);process.exitCode=1});
